=== amtul-nazneen/web-programming-languages/XSD_XML/stocks.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<!-- declaration of elements -->
	<xsd:element name="tickerSymbol">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][A-Z][A-Z]" />
				<xsd:maxLength value="3" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<xsd:element name="releaseDate" type="xsd:date" />

	<xsd:element name="price">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:decimal">
					<xsd:attribute name="currency" use="required">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="USD" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="name">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z][a-zA-Z]*( [A-Z][a-zA-Z]*)*" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<xsd:element name="totalEmployees">
		<xsd:simpleType>
			<xsd:restriction base="xsd:positiveInteger" />
		</xsd:simpleType>
	</xsd:element>


	<xsd:element name="country">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string">
				<xsd:pattern value="[A-Z\s]+" />
			</xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<!-- declaration of complex types -->
		<xsd:complexType name="organization">
			<xsd:sequence>
				<xsd:element ref="name" />
				<xsd:element ref="totalEmployees" />
				<xsd:element ref="country" />
			</xsd:sequence>
		</xsd:complexType>
	

	<!-- declaration of complex types -->
	<xsd:element name="stock">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="tickerSymbol" />
				<xsd:element ref="releaseDate" />
				<xsd:element ref="price" />
				<xsd:element name="company" type="organization"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<!-- declaration of complex types -->
	<xsd:element name="stocks">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="stock" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== amtul-nazneen/web-programming-languages/XSD_XML/stocks.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<stocks xsi:noNamespaceSchemaLocation="stocks.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <stock>
    <tickerSymbol>CRI</tickerSymbol>
    <releaseDate>2019-01-09</releaseDate>
    <price currency="USD">747.2</price>
    <company>
      <name>ExxonMobil</name>
      <totalEmployees>121</totalEmployees>
      <country>ARMENIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>GJA</tickerSymbol>
    <releaseDate>2015-12-21</releaseDate>
    <price currency="USD">304.6</price>
    <company>
      <name>Roche Holding</name>
      <totalEmployees>57</totalEmployees>
      <country>BELARUS</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>KSF</tickerSymbol>
    <releaseDate>2018-11-02</releaseDate>
    <price currency="USD">196.9</price>
    <company>
      <name>Roche Holding</name>
      <totalEmployees>116</totalEmployees>
      <country>AZERBAIJAN</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>ESI</tickerSymbol>
    <releaseDate>2011-02-25</releaseDate>
    <price currency="USD">119.6</price>
    <company>
      <name>Bank Of America</name>
      <totalEmployees>114</totalEmployees>
      <country>ANGOLA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>DJK</tickerSymbol>
    <releaseDate>2006-08-21</releaseDate>
    <price currency="USD">256.8</price>
    <company>
      <name>Procter Gamble</name>
      <totalEmployees>70</totalEmployees>
      <country>AFGHANISTAN</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>QXD</tickerSymbol>
    <releaseDate>2022-12-25</releaseDate>
    <price currency="USD">221.3</price>
    <company>
      <name>Walt Disney</name>
      <totalEmployees>130</totalEmployees>
      <country>AFGHANISTAN</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>JGV</tickerSymbol>
    <releaseDate>2019-10-06</releaseDate>
    <price currency="USD">263.3</price>
    <company>
      <name>Ping An Insurance Group</name>
      <totalEmployees>45</totalEmployees>
      <country>BELARUS</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>XZS</tickerSymbol>
    <releaseDate>2013-06-07</releaseDate>
    <price currency="USD">496.0</price>
    <company>
      <name>Verizon Communications</name>
      <totalEmployees>61</totalEmployees>
      <country>BARBADOS</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>QFH</tickerSymbol>
    <releaseDate>2013-06-23</releaseDate>
    <price currency="USD">240.6</price>
    <company>
      <name>ExxonMobil</name>
      <totalEmployees>91</totalEmployees>
      <country>ANGOLA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>WQM</tickerSymbol>
    <releaseDate>2007-08-06</releaseDate>
    <price currency="USD">808.6</price>
    <company>
      <name>Cisco Systems</name>
      <totalEmployees>127</totalEmployees>
      <country>AUSTRIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>JDU</tickerSymbol>
    <releaseDate>2018-10-05</releaseDate>
    <price currency="USD">277.4</price>
    <company>
      <name>Cisco Systems</name>
      <totalEmployees>70</totalEmployees>
      <country>ARGENTINA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>RFF</tickerSymbol>
    <releaseDate>2013-08-01</releaseDate>
    <price currency="USD">776.0</price>
    <company>
      <name>AT T</name>
      <totalEmployees>106</totalEmployees>
      <country>ANDORRA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>RPI</tickerSymbol>
    <releaseDate>2007-01-09</releaseDate>
    <price currency="USD">924.8</price>
    <company>
      <name>Taiwan Semiconductor</name>
      <totalEmployees>110</totalEmployees>
      <country>ANGOLA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>BDF</tickerSymbol>
    <releaseDate>2008-01-26</releaseDate>
    <price currency="USD">844.2</price>
    <company>
      <name>Intel</name>
      <totalEmployees>92</totalEmployees>
      <country>BARBADOS</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>PSB</tickerSymbol>
    <releaseDate>2014-07-12</releaseDate>
    <price currency="USD">291.5</price>
    <company>
      <name>Taiwan Semiconductor</name>
      <totalEmployees>117</totalEmployees>
      <country>ARMENIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>BNO</tickerSymbol>
    <releaseDate>2011-08-07</releaseDate>
    <price currency="USD">259.0</price>
    <company>
      <name>Intel</name>
      <totalEmployees>109</totalEmployees>
      <country>ALBANIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>NUY</tickerSymbol>
    <releaseDate>2016-11-08</releaseDate>
    <price currency="USD">782.5</price>
    <company>
      <name>Procter Gamble</name>
      <totalEmployees>41</totalEmployees>
      <country>ALBANIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>SAT</tickerSymbol>
    <releaseDate>2008-10-23</releaseDate>
    <price currency="USD">800.9</price>
    <company>
      <name>Mastercard</name>
      <totalEmployees>82</totalEmployees>
      <country>AUSTRALIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>INR</tickerSymbol>
    <releaseDate>2020-03-01</releaseDate>
    <price currency="USD">974.4</price>
    <company>
      <name>Roche Holding</name>
      <totalEmployees>109</totalEmployees>
      <country>ALBANIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>FMP</tickerSymbol>
    <releaseDate>2019-04-17</releaseDate>
    <price currency="USD">220.5</price>
    <company>
      <name>JPMorgan Chase</name>
      <totalEmployees>70</totalEmployees>
      <country>BARBADOS</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>QVB</tickerSymbol>
    <releaseDate>2006-12-16</releaseDate>
    <price currency="USD">948.7</price>
    <company>
      <name>Alibaba</name>
      <totalEmployees>135</totalEmployees>
      <country>ALGERIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>IDT</tickerSymbol>
    <releaseDate>2014-08-27</releaseDate>
    <price currency="USD">151.8</price>
    <company>
      <name>Microsoft</name>
      <totalEmployees>92</totalEmployees>
      <country>BANGLADESH</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>XLP</tickerSymbol>
    <releaseDate>2016-11-01</releaseDate>
    <price currency="USD">516.2</price>
    <company>
      <name>Pfizer</name>
      <totalEmployees>138</totalEmployees>
      <country>ANDORRA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>AWN</tickerSymbol>
    <releaseDate>2023-01-07</releaseDate>
    <price currency="USD">911.2</price>
    <company>
      <name>JPMorgan Chase</name>
      <totalEmployees>138</totalEmployees>
      <country>ARMENIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>GSS</tickerSymbol>
    <releaseDate>2014-05-05</releaseDate>
    <price currency="USD">155.7</price>
    <company>
      <name>Samsung Electronics</name>
      <totalEmployees>120</totalEmployees>
      <country>BAHRAIN</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>AOV</tickerSymbol>
    <releaseDate>2012-07-08</releaseDate>
    <price currency="USD">993.5</price>
    <company>
      <name>Intel</name>
      <totalEmployees>54</totalEmployees>
      <country>AUSTRIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>QCO</tickerSymbol>
    <releaseDate>2018-01-12</releaseDate>
    <price currency="USD">164.7</price>
    <company>
      <name>Verizon Communications</name>
      <totalEmployees>108</totalEmployees>
      <country>ARMENIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>DRP</tickerSymbol>
    <releaseDate>2005-05-13</releaseDate>
    <price currency="USD">266.3</price>
    <company>
      <name>Cisco Systems</name>
      <totalEmployees>63</totalEmployees>
      <country>AUSTRIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>CPK</tickerSymbol>
    <releaseDate>2021-01-11</releaseDate>
    <price currency="USD">472.5</price>
    <company>
      <name>Pfizer</name>
      <totalEmployees>60</totalEmployees>
      <country>ARMENIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>NXI</tickerSymbol>
    <releaseDate>2011-06-23</releaseDate>
    <price currency="USD">834.6</price>
    <company>
      <name>Walmart</name>
      <totalEmployees>124</totalEmployees>
      <country>BARBADOS</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>QWM</tickerSymbol>
    <releaseDate>2014-01-18</releaseDate>
    <price currency="USD">802.3</price>
    <company>
      <name>Apple</name>
      <totalEmployees>99</totalEmployees>
      <country>ALGERIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>XGI</tickerSymbol>
    <releaseDate>2007-08-19</releaseDate>
    <price currency="USD">296.7</price>
    <company>
      <name>Intel</name>
      <totalEmployees>71</totalEmployees>
      <country>ANDORRA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>TJB</tickerSymbol>
    <releaseDate>2020-09-02</releaseDate>
    <price currency="USD">384.8</price>
    <company>
      <name>Facebook</name>
      <totalEmployees>51</totalEmployees>
      <country>ALGERIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>PSX</tickerSymbol>
    <releaseDate>2014-01-25</releaseDate>
    <price currency="USD">646.2</price>
    <company>
      <name>Johnson Johnson</name>
      <totalEmployees>106</totalEmployees>
      <country>AUSTRALIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>TVE</tickerSymbol>
    <releaseDate>2017-10-10</releaseDate>
    <price currency="USD">224.6</price>
    <company>
      <name>Samsung Electronics</name>
      <totalEmployees>123</totalEmployees>
      <country>ALGERIA</country>
    </company>
  </stock>
  <stock>
    <tickerSymbol>LAG</tickerSymbol>
    <releaseDate>2016-01-16</releaseDate>
    <price currency="USD">386.7</price>
